### ISSUE TITLE
Informació de fitxers al fer Share

### ISSUE THREAD

**Issue by projeccions-eulalia** [projeccionspdc/pdc-issues#64]
## Info queda darrere de la finestra per triar més contingut al fer Share
* Comparteixo un metadocument i vull afegir més contingut
* Cerco per tag "presentation", em surten diferents arxius, vull saber què son perquè només en veig una part
* Clico la "i" per informació però queda darrere (adjunto captura de pantalla) i no es pot llegir la informació
 ![FRANS Americas](https://user-images.githubusercontent.com/12810851/119682656-5995ae00-be43-11eb-867c-a7cf929d1053.png)

## web
* **Usuari**: Luli
* **Plataforma/Plataformes**: solutionHUB
* **Client**: Navegador web
* **Dispositiu**: Mac
* **Versió**: 
* **Versió PDC**:

**Comment by pdc-frans** [comment]
Corregit a https://github.com/projeccionspdc/frontend-react-pdc/commit/7e0952365dcb168610a6c29a8ef00a3483f6e7c8
