### ISSUE TITLE
Data d’actualització dels continguts a la library

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#68]
Quan s'actulitza contingut a la library, a vegades no s'actulitza la data del primer file que es va penjar, o d'alguna actulització antiga
![unnamed (1)](https://user-images.githubusercontent.com/33124036/141451317-a890de10-a0df-47b2-a45d-c21f535d09b3.png)

**Comment by pdc-frans** [comment]
Hola Àlex!
això que veus aquí és la data de creació, no la d'actualització. Podem mirar si posem les dues, com vegis.

**Comment by projeccions-alex** [comment]
Amb la data d'actulització tenim suficient! És per confirmar que s'ha actualitzat el file i alhora de fer revisions, veure quan es van penjar aquells documents.
