### ISSUE TITLE
No es pot moure algún contingut a la PDC La Meta

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#71]
En diferents categories no puc moure el contingut que hi ha per canviar l'ordre.
Passa a alguns llocs, uns són:
https://lameta.pdcvallcompanys.com/category/edit/_O6T0FAVb
https://lameta.pdcvallcompanys.com/category/edit/rkGvWsQQQ

El que passa és que quan canvies d'ordre el contingut, al cap d'un segon torna a com estava abans.

**Comment by pdc-frans** [comment]
Ja hauria de funcionar ;)
