### ISSUE TITLE
Accès PDC Avigal

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#75]
No podem accedir a la [PDC Avigal](https://avigal.pdcvallcompanys.com) 

- Monica, te accés però no aconsegueix accedir
- Alex, sense accés i no puc afegir-me a la plataforma des del cc

**Comment by pdc-frans** [comment]
La Mònica i l'Ana son usuaris (no eren admin ara sí). T'acabo de convidar
