### ISSUE TITLE
No visualització Home PDC Zyrcular

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#77]
## Descripció del problema
L'usuari del Cesc, registrat a la plataforma, quan vol accedir a la Home del contingut a través del boto "acceder" li surt la pantalla en blanc i nomès amb logo. 
Adjunto captura de pantalla:
![Imagen 24-2-22 a las 17 09](https://user-images.githubusercontent.com/33124036/155563244-43625daf-4dcc-45d5-b022-efe1635b7533.jpg)

**Comment by pdc-frans** [comment]
Hola Àlex, té permisos per veure el contingut? No estan en cap grup especial?

**Comment by projeccions-alex** [comment]
Ho he mirat, i la home esta oberta per a tothom
![Screen Shot 2022-02-24 at 17 18 50](https://user-images.githubusercontent.com/33124036/155564135-3dae589e-95e4-4c1d-b891-9954a9854112.png)

**Comment by projeccions-alex** [comment]
Ara veig que cada una de les categories de la home té una visibilitat diferent

Serà per això que no ho pot veure, oi?

**Comment by pdc-frans** [comment]
SI no té visibilitat sobre els grups és això ^ ^
