### ISSUE TITLE
Error alhora de crear una plataforma

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#78]
## Després d'omplir tots el camps per crear una plataforma a meetpdc, em surt un error (adjunto captura de pantalla)

 
![Screen Shot 2022-03-22 at 10 52 09](https://user-images.githubusercontent.com/33124036/159454478-b48331e6-6779-4603-a96a-b22b1d87fe62.png)

**Comment by pdc-frans** [comment]
Els dominis cc, www, meetpdc, pdc i setup estan reservats per l'aplicació
