### ISSUE TITLE
Metadocumetn solutionHUB France que no es veu en modo editor

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#84]
Actualitzant els mapes de França, em aquest metadocument (https://france.dbschenkersolutionhub.com/metadocument/edit/gMFYItXBm), se'ns queda la pantalla en blan.

Adjunto captura de pantalla
<img width="1444" alt="Captura de pantalla 2022-06-20 a les 12 58 25" src="https://user-images.githubusercontent.com/33124036/174587717-0e513ccc-359a-41e4-896c-20cdcc6d91b9.png">

**Comment by pdc-frans** [comment]
Us he restaurat la còpia del matí.
