### ISSUE TITLE
PDC Ores - Moure metadocuments

### ISSUE THREAD

**Issue by projeccions-alex** [projeccionspdc/pdc-issues#87]
A la categoria (https://ores.pdcvallcompanys.com/category/edit/E7VZTzVaL), intentem moure el metadocument Septiembre 2022 al primer de tots, però sempre torna a l'últim.

Ens ho pots arreglar o dir que podem fer?
Merci

<img width="1585" alt="Captura de pantalla 2022-09-06 a les 9 48 55" src="https://user-images.githubusercontent.com/33124036/188578638-c40ef624-1f26-4f59-ac7c-75902d0c34c1.png">

**Comment by pdc-frans** [comment]
Pots provar a veure si ja funciona?

**Comment by projeccions-alex** [comment]
Solucionat, merci!!
